Fix the cloudflare_worker_routes
Fix error when trying to apply cloudflare_worker_route with a pattern with * host:

Error: error updating worker route: You cannot use a wildcard host without Cloudflare for SaaS. Enable Cloudflare for SaaS for your zone (https://developers.cloudflare.com/cloudflare-for-platforms/cloudflare-for-saas/start/enable/) and try again. (100327)

Also use for_each to create separate routes according to the Caution block of https://developers.cloudflare.com/workers/configuration/routing/routes/: “Caution: Because * matches zero or more of any character (not just subdomains), *example.com will also match hostnames that are not subdomains of example.com. If you only want to match example.com and its subdomains, use two separate routes (example.com/* and *.example.com/*) instead.”